# Generated by Django 4.2.16 on 2024-09-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netpitch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Writer', 'Writer'), ('Producer', 'Producer')], max_length=10),
        ),
        migrations.CreateModel(
            name='PitchDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('pitch_type', models.CharField(choices=[('Film', 'Film'), ('TV Show', 'TV Show')], max_length=10)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='netpitch.genre')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netpitch.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netpitch.pitchdeck')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netpitch.profile')),
            ],
        ),
    ]
