# Generated by Django 4.2.16 on 2024-09-25 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netpitch', '0002_genre_alter_profile_user_type_pitchdeck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pitch_images/'),
        ),
        migrations.AddField(
            model_name='pitchdeck',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdeck',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netpitch.genre'),
        ),
        migrations.AlterField(
            model_name='pitchdeck',
            name='pitch_type',
            field=models.CharField(choices=[('Film', 'Film'), ('TV Show', 'TV Show')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pitchdeck',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pitchdeck',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_decks', to=settings.AUTH_USER_MODEL),
        ),
    ]
