# Generated by Django 4.2.16 on 2024-09-27 14:44

from django.db import migrations

def add_genres(apps, schema_editor):
    Genre = apps.get_model('netpitch', 'Genre')
    genres = [
        "Action", "Crime", "Drama", "Fantasy", "Horror", "Comedy",
        "Romance", "Science Fiction", "Sports", "Thriller", "Mystery",
        "War", "Western"
    ]
    for genre in genres:
        Genre.objects.create(name=genre)

class Migration(migrations.Migration):

    dependencies = [
        ('netpitch', '0003_pitchdeck_image_pitchdeck_theme_and_more'),
    ]

    operations = [
        migrations.RunPython(add_genres),
    ]