# Generated by Django 4.2.16 on 2024-09-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netpitch', '0003_pitchdeck_theme_alter_pitchdeck_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pitch_images/'),
        ),
    ]
