# Generated by Django 4.2.16 on 2024-10-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netpitch', '0005_collaborationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cleared', 'Cleared')], default='Pending', max_length=10),
        ),
    ]
